name: route39_workspace
publish_to: "none"
environment:
  sdk: ">=3.9.0 <4.0.0"
workspace:
  - apps/rider-frontend
  - apps/driver-frontend
  - libs/flutter_common
  - libs/flutter_localizations

dependency_overrides:
  logger: any
  generic_map: ">=0.12.0"
  dotted_border: ">=3.0.0"
  maplibre_gl: ">=0.27.0"
  maplibre_gl_web: ">=0.27.0"
  maplibre_gl_platform_interface: ">=0.27.0"
