name: route39_workspace
publish_to: "none"
environment:
  sdk: ">=3.9.0 <4.0.0"
workspace:
  - apps/rider-frontend
  - apps/driver-frontend
  - libs/flutter_common
  - libs/flutter_localizations

dependency_overrides:
  logger: any
