query ActiveOrders {
  activeOrders {
    ...ActiveOrder
  }
}

mutation CreateOrder($input: CreateOrderInput!) {
  createOrder(input: $input) {
    ...ActiveOrder
  }
}

mutation CancelOrder(
  $orderId: ID!
  $cancelReasonId: ID
  $cancelReasonNote: String
) {
  cancelOrder(
    orderId: $orderId
    cancelReasonId: $cancelReasonId
    cancelReasonNote: $cancelReasonNote
  )
}

mutation UpdateLastSeenMessagesAt($orderId: ID!) {
  updateLastSeenMessagesAt(orderId: $orderId)
}

mutation updateOrderWaitTime($orderId: ID!, $waitTime: Int!) {
  updateOrderWaitTime(orderId: $orderId, waitTime: $waitTime) {
    totalCost
    waitTime
  }
}

query verifyCouponCode($code: String!) {
  couponInfo(code: $code) {
    description
    title
  }
}

mutation initiateCall($orderId: ID!) {
  initiateCall(orderId: $orderId)
}

mutation applyCoupon($orderId: ID!, $code: String!) {
  applyCoupon(orderId: $orderId, couponCode: $code) {
    couponDiscount
    totalCost
  }
}

query CancelReasons {
  cancelReasons {
    ...cancelReason
  }
}

mutation CreateRazorpayRideOrder($orderId: ID!) {
  createRazorpayRideOrder(orderId: $orderId) {
    orderId
    amount
    currency
    keyId
  }
}

mutation VerifyRazorpayRidePayment(
  $orderId: ID!
  $razorpayOrderId: String!
  $razorpayPaymentId: String!
  $razorpaySignature: String!
) {
  verifyRazorpayRidePayment(
    orderId: $orderId
    razorpayOrderId: $razorpayOrderId
    razorpayPaymentId: $razorpayPaymentId
    razorpaySignature: $razorpaySignature
  )
}
